"""AST-validated, subprocess-isolated execution of LLM-generated pandas code.

See spec/architecture.md -> "Sandboxing Approach for LLM-Generated Code
Execution" (binding). Every `analyze(df)` function generated by `generate_code`
runs here: statically validated with `ast.parse` before anything executes,
then run in an isolated `multiprocessing.get_context("spawn")` subprocess
(portable across the Windows dev environment and Linux deployment) with a
hard timeout, a restricted builtins namespace, and the real `DataFrame`
pre-bound as `df`. Tabular results are capped to `head(50)` before returning.
"""
import ast
import builtins as _builtins_module
import contextlib
import io
import json
import multiprocessing as mp
import os
import sys
import time
from pathlib import Path
from typing import Any

# Children spawned via `multiprocessing.get_context("spawn")` re-import this
# module by qualified name to unpickle `_child_run`. On Windows in particular,
# that import must succeed even though the child process doesn't inherit the
# parent's in-memory `sys.path` mutations (e.g. pytest's `pythonpath` ini
# option) -- only environment variables survive. Fix PYTHONPATH at import
# time so `import sandbox.executor` (and the graph's `from db.models import
# ...`-style top-level imports it may indirectly trigger) work in the child.
_SRC_DIR = str(Path(__file__).resolve().parent.parent)
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)
_existing_pythonpath = os.environ.get("PYTHONPATH", "")
if _SRC_DIR not in _existing_pythonpath.split(os.pathsep):
    os.environ["PYTHONPATH"] = (
        _SRC_DIR + (os.pathsep + _existing_pythonpath if _existing_pythonpath else "")
    )

ALLOWED_IMPORTS = {"pandas", "numpy", "math", "re", "statistics", "datetime"}
FORBIDDEN_NAMES = {
    "os", "sys", "subprocess", "socket", "pathlib", "shutil",
    "open", "eval", "exec", "compile", "__import__",
}

_SAFE_BUILTIN_NAMES = [
    "abs", "all", "any", "bool", "dict", "enumerate", "float", "int", "len",
    "list", "max", "min", "print", "range", "round", "set", "sorted", "str",
    "sum", "tuple", "zip", "type", "isinstance", "Exception", "ValueError",
    "TypeError", "KeyError", "IndexError", "StopIteration", "AttributeError",
    "RuntimeError", "ZeroDivisionError", "NotImplementedError",
]
_SAFE_BUILTINS: dict[str, Any] = {
    name: getattr(_builtins_module, name)
    for name in _SAFE_BUILTIN_NAMES
    if hasattr(_builtins_module, name)
}
# Required by the `import` statement's bytecode (IMPORT_NAME calls
# `__builtins__.__import__`) even though the code's own AST can never
# reference the identifier `__import__` directly (blocked below).
_SAFE_BUILTINS["__import__"] = _builtins_module.__import__

_MAX_RESULT_ROWS = 50


class SandboxValidationError(Exception):
    """Raised when generated code fails static validation (never executed)."""


def validate_code(code: str) -> None:
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        raise SandboxValidationError(f"Code has a syntax error: {exc}") from exc

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]
                if root not in ALLOWED_IMPORTS:
                    raise SandboxValidationError(f"Import of module '{alias.name}' is not allowed")
        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".")[0]
            if root not in ALLOWED_IMPORTS:
                raise SandboxValidationError(f"Import of module '{node.module}' is not allowed")
        elif isinstance(node, ast.Name):
            if node.id in FORBIDDEN_NAMES:
                raise SandboxValidationError(f"Use of '{node.id}' is not allowed")
        elif isinstance(node, ast.Attribute):
            if node.attr.startswith("__") and node.attr.endswith("__"):
                raise SandboxValidationError(f"Dunder attribute access '.{node.attr}' is not allowed")


def _cap_result(result: Any) -> tuple[Any, bool]:
    try:
        import pandas as pd
    except ImportError:  # pragma: no cover - pandas is a hard dependency
        pd = None

    if pd is not None and isinstance(result, pd.DataFrame):
        truncated = len(result) > _MAX_RESULT_ROWS
        capped = result.head(_MAX_RESULT_ROWS)
        return json.loads(capped.to_json(orient="records", date_format="iso")), truncated
    if pd is not None and isinstance(result, pd.Series):
        truncated = len(result) > _MAX_RESULT_ROWS
        capped = result.head(_MAX_RESULT_ROWS)
        return json.loads(capped.to_json(date_format="iso")), truncated
    if isinstance(result, list):
        truncated = len(result) > _MAX_RESULT_ROWS
        return result[:_MAX_RESULT_ROWS], truncated
    return result, False


def _child_run(code: str, df: Any, queue: "mp.Queue") -> None:
    stdout_buf = io.StringIO()
    try:
        validate_code(code)  # defense in depth: re-validated inside the child too
        namespace: dict[str, Any] = {"__builtins__": _SAFE_BUILTINS, "df": df}
        start = time.time()
        with contextlib.redirect_stdout(stdout_buf):
            exec(code, namespace)
            analyze = namespace.get("analyze")
            if analyze is None:
                queue.put({
                    "result": None, "stdout": stdout_buf.getvalue(),
                    "error": "No analyze(df) function was defined", "duration_ms": 0,
                })
                return
            result = analyze(df)
        duration_ms = int((time.time() - start) * 1000)
        capped_result, truncated = _cap_result(result)
        if isinstance(capped_result, dict):
            capped_result = dict(capped_result)
            capped_result["truncated"] = truncated
        queue.put({
            "result": capped_result, "stdout": stdout_buf.getvalue(),
            "error": None, "duration_ms": duration_ms,
        })
    except Exception as exc:
        queue.put({
            "result": None, "stdout": stdout_buf.getvalue(),
            "error": f"{type(exc).__name__}: {exc}", "duration_ms": 0,
        })


def run_sandboxed(
    code: str, df: Any, timeout_seconds: int
) -> tuple[dict | None, str, str | None, int]:
    """Validate then execute `analyze(df)` in an isolated subprocess.

    Returns (result, stdout, error, duration_ms).
    """
    try:
        validate_code(code)
    except SandboxValidationError as exc:
        return None, "", str(exc), 0

    ctx = mp.get_context("spawn")
    queue: "mp.Queue" = ctx.Queue()
    process = ctx.Process(target=_child_run, args=(code, df, queue))
    start = time.time()
    process.start()
    process.join(timeout_seconds)

    if process.is_alive():
        process.terminate()
        process.join()
        duration_ms = int((time.time() - start) * 1000)
        return None, "", f"timed out after {timeout_seconds}s", duration_ms

    if not queue.empty():
        payload = queue.get()
        return payload.get("result"), payload.get("stdout", ""), payload.get("error"), payload.get("duration_ms", 0)

    duration_ms = int((time.time() - start) * 1000)
    return None, "", f"Sandbox process exited unexpectedly (code {process.exitcode})", duration_ms
